# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_article_fetched_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
            ],
        ),
    ]
